// v0 scaffold for: No AI irrigation optimization (real-time water scheduling)
// Generated by batch_00 audit gaps. Persists to lazy `gap_features` table when DB available.
// TODO: configure credentials
const express = require('express');
const router = express.Router();
const FEATURE_TITLE = "No AI irrigation optimization (real-time water scheduling)";
let authMiddleware = null;
try {
  authMiddleware = require('../middleware/auth');
} catch (e) {
  authMiddleware = null;
}
if (authMiddleware) {
  // Some projects export the middleware directly; others as { authenticateToken }
  const mw = typeof authMiddleware === 'function' ? authMiddleware : (authMiddleware.authenticateToken || authMiddleware.default || null);
  if (mw) router.use(mw);
}

let db = null;
try {
  db = require('../db');
} catch (e) {
  db = null;
}

async function ensureTable() {
  if (!db) return;
  try {
    const sql = `CREATE TABLE IF NOT EXISTS gap_features (
      id SERIAL PRIMARY KEY,
      project TEXT,
      slug TEXT,
      input JSONB,
      output JSONB,
      created_at TIMESTAMP DEFAULT NOW()
    )`;
    if (typeof db.query === 'function') {
      await db.query(sql);
    }
  } catch (err) {
    // best-effort; ignore in v0
  }
}

async function persist(input, output) {
  if (!db) return;
  try {
    await ensureTable();
    if (typeof db.query === 'function') {
      await db.query(
        'INSERT INTO gap_features(project, slug, input, output) VALUES ($1, $2, $3, $4)',
        ['AIAgricultureAssistant', 'ai-irrigation-optimization-real-time', JSON.stringify(input), JSON.stringify(output)]
      );
    }
  } catch (err) {
    // ignore
  }
}

async function callOpenRouter(prompt) {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    return null;
  }
  try {
    const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: process.env.OPENROUTER_MODEL || 'anthropic/claude-3.5-sonnet',
        messages: [
          { role: 'system', content: `You are an assistant for the feature: ${FEATURE_TITLE}.` },
          { role: 'user', content: prompt },
        ],
      }),
    });
    if (!res.ok) {
      return { error: `OpenRouter HTTP ${res.status}` };
    }
    const json = await res.json();
    return { choices: json?.choices, model: json?.model };
  } catch (err) {
    return { error: err.message };
  }
}

function buildIrrigationSchedule(input) {
  const crop = input.crop || input.crop_type || 'crop';
  const soilMoisture = Number(input.soil_moisture_pct || input.moisture_pct || 24);
  const targetMoisture = Number(input.target_moisture_pct || 32);
  const fieldAreaHa = Number(input.field_area_ha || input.hectares || 10);
  const evapMm = Number(input.evapotranspiration_mm || input.et_mm || 5);
  const rainMm = Number(input.forecast_rain_mm || input.rain_mm || 0);
  const deficitPct = Math.max(0, targetMoisture - soilMoisture);
  const waterDepthMm = Math.max(0, deficitPct * 2.2 + evapMm - rainMm);
  const volumeM3 = waterDepthMm * fieldAreaHa * 10;
  const urgency = waterDepthMm > 25 ? 'critical' : waterDepthMm > 12 ? 'schedule_today' : waterDepthMm > 3 ? 'monitor' : 'skip';

  return {
    mode: 'deterministic_fallback',
    crop,
    urgency,
    recommendation: urgency === 'skip'
      ? 'Skip irrigation; forecast rain and current moisture cover near-term demand.'
      : `Apply ${waterDepthMm.toFixed(1)} mm across ${fieldAreaHa} ha (${volumeM3.toFixed(0)} m3).`,
    schedule: {
      start_window: urgency === 'critical' ? 'next cool low-wind window' : 'overnight or early morning',
      duration_hours_estimate: Number(Math.max(1, waterDepthMm / Number(input.system_mm_per_hour || 8)).toFixed(1)),
      pulse_strategy: waterDepthMm > 20 ? 'split into 2 pulses to reduce runoff' : 'single pass acceptable',
    },
    drivers: {
      soil_moisture_pct: soilMoisture,
      target_moisture_pct: targetMoisture,
      evapotranspiration_mm: evapMm,
      forecast_rain_mm: rainMm,
      field_area_ha: fieldAreaHa,
    },
    safeguards: [
      'Pause if wind exceeds nozzle drift threshold.',
      'Recheck soil moisture 6-12 hours after irrigation.',
      'Do not irrigate immediately before pesticide application unless label allows it.',
    ],
  };
}

router.get('/health', (req, res) => {
  res.json({ feature: 'ai-irrigation-optimization-real-time', status: 'ok', version: 'v0', kind: 'gap' });
});

router.post('/run', async (req, res) => {
  try {
    const input = req.body || {};
    const prompt = typeof input.input === 'string' ? input.input : JSON.stringify(input);
    const aiResult = await callOpenRouter(prompt);
    const fallback = aiResult ? null : buildIrrigationSchedule(input);
    const output = {
      feature: 'ai-irrigation-optimization-real-time',
      title: FEATURE_TITLE,
      receivedKeys: Object.keys(input),
      ai: aiResult,
      result: fallback || aiResult,
    };
    persist(input, output).catch(() => {});
    res.json({ success: true, result: output });
  } catch (err) {
    console.error('[gap-ai-irrigation-optimization-real-time] error', err);
    res.status(500).json({ success: false, error: err.message });
  }
});

module.exports = router;
